import type { PluginClientContext } from "@getpaseo/plugin/client";

/**
 * Wye themes for Paseo — ported from phyzess/vscode-theme-wye.
 *
 * Generated by scripts/sync-theme.mjs. Do not edit the palette by hand: run
 * `node scripts/sync-theme.mjs` after upstream changes a color.
 *
 * Paseo takes eight seed colors per theme and derives surfaces, panels, menus,
 * diffs, status colors, syntax highlighting and terminal colors from them, so
 * Wye's exact syntax mapping (green strings, cyan keywords, orange variables) is
 * intentionally not reproduced here — only the surface identity is: near-black
 * backgrounds, the lime primary, the pink focus ring.
 *
 * The VS Code *-italic variants have no Paseo equivalent (a Paseo theme carries
 * no typography axis) and are not ported.
 *
 * Each seed maps onto the upstream theme like this:
 *   background      <- editor.background
 *   foreground      <- editor.foreground
 *   raised          <- list.hoverBackground / activeBackground (cards, popovers, hovered rows)
 *   control         <- lowBackground / lowActiveBackground (inputs, secondary fills)
 *   border          <- lowBorder or WyeThemes.border (VS Code keeps borders background-colored;
 *                      Paseo needs a visible surface boundary, so the theme's own value is used)
 *   accent          <- WyeThemes.primary (button.background)
 *   mutedForeground <- WyeThemes.secondaryForeground, or comment for the light variants
 *                      (secondaryForeground is translucent there, and Paseo requires opaque hex)
 *   ring            <- WyeThemes.pink (focusBorder)
 */
export default function contribute(client: PluginClientContext) {
  client.addTheme({
    id: "wye-dark",
    name: "Wye Dark",
    appearance: "dark",
    colors: {
      background: "#151515",
      foreground: "#e5e5e5",
      raised: "#252b2a",
      control: "#292929",
      border: "#222222",
      accent: "#bde46f",
      mutedForeground: "#b3b1ad",
      ring: "#ff57b3",
    },
  });

  client.addTheme({
    id: "wye-dark-soft",
    name: "Wye Dark Soft",
    appearance: "dark",
    colors: {
      background: "#222222",
      foreground: "#e5e5e5",
      raised: "#292929",
      control: "#252b2a",
      border: "#292929",
      accent: "#bde46f",
      mutedForeground: "#b3b1ad",
      ring: "#ff57b3",
    },
  });

  client.addTheme({
    id: "wye-black",
    name: "Wye Black",
    appearance: "dark",
    colors: {
      background: "#000000",
      foreground: "#e5e5e5",
      raised: "#050505",
      control: "#111111",
      border: "#151515",
      accent: "#bde46f",
      mutedForeground: "#b3b1ad",
      ring: "#ff57b3",
    },
  });

  client.addTheme({
    id: "wye-light",
    name: "Wye Light",
    appearance: "light",
    colors: {
      background: "#ffffff",
      foreground: "#393a34",
      raised: "#f7f7f7",
      control: "#f1f0e9",
      border: "#f0f0f0",
      accent: "#1c6b48",
      mutedForeground: "#a0ada0",
      ring: "#fe70bc",
    },
  });

  client.addTheme({
    id: "wye-light-soft",
    name: "Wye Light Soft",
    appearance: "light",
    colors: {
      background: "#f1f0e9",
      foreground: "#393a34",
      raised: "#e7e5db",
      control: "#e7e5db",
      border: "#e7e5db",
      accent: "#1c6b48",
      mutedForeground: "#a0ada0",
      ring: "#fe70bc",
    },
  });

  return () => {};
}
